POST http://localhost:8080/realms/xsl-app/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded


grant_type=password&username=os336&password=1234&client_id=checked_tools&client_secret=RWQkPMmf8t2qKxzVmdTAT7zrLw7pIewe

###

#POST http://0.0.0.0:8080/realms/xsl-app/protocol/openid-connect/token
#Content-Type: application/x-www-form-urlencoded
#
#
#grant_type=refresh_token&client_id=checked_tools&refresh_token=eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyMWZiNDNkYi1kMDcxLTQ2MzItODQ0Ny0yYjY3YzVlZGI5MzQifQ&client_secret=RWQkPMmf8t2qKxzVmdTAT7zrLw7pIewe
####


POST http://0.0.0.0:8080/realms/xsl-app/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded


grant_type=client_credentials&client_id=checked_tools&client_secret=RWQkPMmf8t2qKxzVmdTAT7zrLw7pIewe
###
