server.port=8081
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

ref_dictionary_path=C:/app-data/refDictionary.json
dictionary_path=C:/app-data/dictionary.json